-- Lab 6 · Your own check, as a query test. The steps: labs/lab6.md
-- A query test returns the bad rows. No rows back means that the test passes.
-- Write your query below. tests/lab1_updated_before_placed.sql shows the shape.
-- Or write a Soda check in soda/my_check.yml instead. One of the two is enough.
